//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4952
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Lehrgang {
    
    private Termin[] terminField;
    
    private string titelField;
    
    private string untertitelField;
    
    private string ressortField;
    
    private LehrgangRubrik rubrikField;
    
    private string beschreibungField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Termin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Termin[] Termin {
        get {
            return this.terminField;
        }
        set {
            this.terminField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Titel {
        get {
            return this.titelField;
        }
        set {
            this.titelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Untertitel {
        get {
            return this.untertitelField;
        }
        set {
            this.untertitelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ressort {
        get {
            return this.ressortField;
        }
        set {
            this.ressortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LehrgangRubrik Rubrik {
        get {
            return this.rubrikField;
        }
        set {
            this.rubrikField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Beschreibung {
        get {
            return this.beschreibungField;
        }
        set {
            this.beschreibungField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Termin {

    private string lgNrField;
    
    private string hinweiseField;
    
    private string leitungField;
    
    private System.DateTime meldeschlussField;
    
    private string umfangField;
    
    private string voraussetzungenField;
    
    private string zielgruppeField;
    
    private string kostenField;
    
    private bool juleicaField;

    private bool apField;
    
    private Teil[] teilField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Hinweise {
        get {
            return this.hinweiseField;
        }
        set {
            this.hinweiseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LgNr
    {
        get
        {
            return this.lgNrField;
        }
        set
        {
            this.lgNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Leitung {
        get {
            return this.leitungField;
        }
        set {
            this.leitungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime Meldeschluss {
        get {
            return this.meldeschlussField;
        }
        set {
            this.meldeschlussField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Umfang {
        get {
            return this.umfangField;
        }
        set {
            this.umfangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Voraussetzungen {
        get {
            return this.voraussetzungenField;
        }
        set {
            this.voraussetzungenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Zielgruppe {
        get {
            return this.zielgruppeField;
        }
        set {
            this.zielgruppeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Kosten
    {
        get
        {
            return this.kostenField;
        }
        set
        {
            this.kostenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Juleica {
        get {
            return this.juleicaField;
        }
        set {
            this.juleicaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool AP
    {
        get
        {
            return this.apField;
        }
        set
        {
            this.apField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Teil", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Teil[] Teil {
        get {
            return this.teilField;
        }
        set {
            this.teilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Teil {
    
    private LehrgangsDatum beginnField;
    
    private LehrgangsDatum endeField;
    
    private string ortField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LehrgangsDatum Beginn {
        get {
            return this.beginnField;
        }
        set {
            this.beginnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LehrgangsDatum Ende {
        get {
            return this.endeField;
        }
        set {
            this.endeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ort {
        get {
            return this.ortField;
        }
        set {
            this.ortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LehrgangsDatum {
    
    private System.DateTime datumField;
    
    private string wochentagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Wochentag {
        get {
            return this.wochentagField;
        }
        set {
            this.wochentagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum LehrgangRubrik {
    
    /// <remarks/>
    Freizeit,
    
    /// <remarks/>
    Einsatz,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Kinder/Jugend")]
    KinderJugend,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("EH/SAN")]
    EHSAN,
    
    /// <remarks/>
    Organisation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Schwimmen/Retten")]
    SchwimmenRetten,

    Umwelt,

    Wettkampf
}
